### ISSUE TITLE
Issue:  1.1.1 crashes dedicated server Forge 1.15.2 build 31.2.5

### ISSUE THREAD

**Issue by kreezxil** [MoriyaShiine/respawnable-pets#12]
Notes:
     invalid dist DEDICATED_SERVER tried to load something meant for the client

crash report: 
http://paste.ubuntu.com/p/5XZhD2JssK/

fml server latest: 
http://paste.ubuntu.com/p/47qjw6njq8/

**Comment by MoriyaShiine** [comment]
I don't have access to a computer right now, but I know what to do. It'll be fixed either tomorrow or the day after. Thanks!
