### ISSUE TITLE
The gem only toggles in creative mode. Nothing happens in survival

### ISSUE THREAD

**Issue by Nick-McKay** [MoriyaShiine/respawnable-pets#15]
On 1.15, the mod doesn't work at all: punching a mob only toggles respawnability on creative mode.

**Comment by MoriyaShiine** [comment]
This is an incompatibility with Tough as Nails that can't be fixed on my end. I made a fix for TAN on my Discord server that someone has access to, but I can't share it publicly due the license restrictions.

**Comment by MoriyaShiine** [comment]
Another mod you have (Such as Tough as Nails (1.12.2)) is duplicating punches, there isn't much I can do about it.
