### ISSUE TITLE
gem works on horses, but not cats or dogs

### ISSUE THREAD

**Issue by MoonMoonShark** [MoriyaShiine/respawnable-pets#18]
have been using this mod for a while in 1.14 and was able to use the gem on any tamed animal, even those from mods. upgraded the server to 1.15 this weekend and now the gem only seems to work on my horse. have tried it on several different dogs and cats, both vanilla and modded, and none of them seem to do anything. looking at the data file, even the animals i had used the gem on previously are no longer listed to respawn.

**Comment by MoriyaShiine** [comment]
Does this happen on 1.16? Anything less than 1.16 is unsupported.

**Comment by MoonMoonShark** [comment]
i don't know yet. i only just rolled my server up to 1.15, because 1.16 is still being actively developed by mojang, and i didn't want an unstable platform on my server.

**Comment by MoriyaShiine** [comment]
Gonna close this then, if it shows up on 1.16 then message back please.
