### ISSUE TITLE
Could non-sitting pets be teleported to the bed if they were lost?

### ISSUE THREAD

**Issue by copygirl** [MoriyaShiine/respawnable-pets#20]
Losing a pet due to it dying really is one issue that really bothers me but the other that happens often, perhaps even more than death, is losing them due to them getting stuck somewhere out in the world in case they couldn't correctly teleport after you. It's worse if you only notice too late and don't know where or when it happened, potentially losing a pet forever as well.

Would it be possible to have a pet that is "lost" in such a way teleported to the bed on sleeping?

**Comment by MoriyaShiine** [comment]
I tried this in 1.15 but couldn't get it to work, however now that I'm on fabric and have mixins, I can see if it's possible. I'm unsure of how Minecraft deals with unloading entities, so don't get your hopes up, but I'll try :).

**Comment by copygirl** [comment]
Thank you very much. Either way, the mod is already a must-have for me!
