### ISSUE TITLE
Not working with dogs, yet working with cats?

### ISSUE THREAD

**Issue by MechanosG** [MoriyaShiine/respawnable-pets#22]
1.16.4 Fabric.  Punching a tamed cat with the gem shows the message saying it will respawn.  But punching a tamed wolf does not.  I do have mods affecting pets, such as Age of Exile and The Loved Ones, but both mods also affect cats, so I'm not sure why one is working while the other isn't.  I'm guessing it's something related a mod doing something to punching, like some other issues had mentioned, as when I punch a sitting cat it doesn't stand up.  But if I punch a sitting dog, it does stand up.

Have any advice?  Or need any additional info?  If it turns out The Loved Ones is the problem, and compatibility can't be achieved, I'll consider removing it next modpack update.

**Comment by MoriyaShiine** [comment]
It works fine on my end, can you find out which mod is causing this?

**Comment by MechanosG** [comment]
Heya.  So..  I have noticed something new.  This might be related to newly tamed pets?  My wolves now let me use the gem on them properly.  However, I found and tamed a 2nd cat.  And this 2nd cat won't allow the gem to be used on it.  Yet my first cat, right next to it, does allow it.  If my theory is correct, I betting that after some time..  maybe after the chunk is unloaded then reloaded, or maybe after server reset, that the 2nd cat will allow me to use the gem on it also.

![2021-02-01_23 22 53](https://user-images.githubusercontent.com/4360512/106565988-86b10000-64e4-11eb-9caa-e481b21c1084.png)
The cats are pretty identical, yet the one on the left works with the gem and the newly tamed on on the right, does not.

**Comment by Dainja55** [comment]
I have the same issue as the person above. Except the Etheric Gem doesn't work on the wolves or cats, ever. BUT, it does work on horses every time. I haven't tried parrots. I'm using the All of Fabric 3 version 2.6.10, which uses the latest version (1.16.5-1) of respawnable pets. Also, the modpack doesn't use the loved ones, and does not use age of exile.

**Comment by Dainja55** [comment]
OMG it WORKS.

**Comment by Dainja55** [comment]
Actually, it still doesn't work and I don't think this is a problem that has anything to do with chunks. I think the problem has something to do with the gamemode, and therefore maybe ... permissions? 

The respawning toggle works in creative (on and off work fine) seen here:
![2021-03-02_15 09 34](https://user-images.githubusercontent.com/77590002/109727689-a54cfa00-7b69-11eb-99af-d7a7d0c3325e.png)

But here, in survival, it doesn't change anything (I tried this multiple times with other wolves too, all of which had the same issue):

![2021-03-02_15 09 44](https://user-images.githubusercontent.com/77590002/109728016-450a8800-7b6a-11eb-9d51-9b3cef4091c0.png)

**Comment by Dainja55** [comment]
Personally, I don't mind this too much because I'm my own server admin, and I play with a small group of friends. However, I don't think this would be practical on larger servers that are open to the public, where access to creative would have to be given, even if the server was a survival server.

**Comment by Dainja55** [comment]
Okay, I think this is an issue with another mod. After doing some testing, it appears to be so.
