### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by WilliamBlaze** [MoriyaShiine/respawnable-pets#23]
If you'll allow it, could you list on your mod page that the public has permission to convert/recreate your "respawnable pets" mod for use on forge so long as credit to your original fabric mod is given and a link back to your fabric mod creation is included on the forge version's mod page? (again, permitted you allow that sort of thing of your creations.)

Since you made it very clear on the mod page that your not going to do a recreation/and or perform any sort of conversion of this mod itself for forge, nor do you intend on going back to making forge mods, it logically seemed like the thing to do was to ask permissions of if you'll allow the community to create a forge version of the mode ourselves.

I figured it better to ask in advance rather then for anyone to waste time trying the attempt, only to be prevented from the upload later on down the road due to an oversight of forgetting to ask sooner'
(You would be surprised how many mods I've seen go "poof" due to similar circumstances)

**Comment by MoriyaShiine** [comment]
While you are technically allowed to make a forge version due to the license, I would prefer that you not. The forge community has hurt my friends and I too many times, and I wish to not be associated with them at all.
