### ISSUE TITLE
[issue/suggestion] remove hard dependency for 1.16.5

### ISSUE THREAD

**Issue by oliwoli** [MoriyaShiine/respawnable-pets#27]
Hello👋 A friendly suggestion to adjust your fabric.mod.json minecraft dependency from **`1.16.5`** to **`^1.16.2`** as your mod should work from 1.16.2 to 1.16.5.  I briefly tested that too. Would also make it more compatible with modpacks that aren't up to date etc.

**Comment by MoriyaShiine** [comment]
Most modpacks should be on 1.16.5 by now. I'll definitely do this for 1.17 though, I started with hard depending because of Mojang breaking whole mods in multiple minor versions for 1.16
