### ISSUE TITLE
Game crashed when testing several different mods - crash when spawning wither in creative

### ISSUE THREAD

**Issue by rustedgoldmc** [MoriyaShiine/respawnable-pets#29]
I was testing mods together for use on a server I plan to help make. A mod I have installed, the Rat's Mischief mod, is able to take down a wither ridiculously quickly. I decided to test whether another mod I installed, a dog armor mod, could also take down a wither. I turned off mob griefing so nothing could escape and spawned a wither in a roughly 16x16x8 glass container with about ten dogs (all in netherite armor) in it and as soon as the wither made the preliminary explosion the game crashed. All the dogs were mine and were able to respawn after death. The crash error code was "The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
Exit Code: -1". I tested it again with only six dogs and it worked without crashing, but then tried with all of them another time and it crashed again. I can kill dogs I own that are in netherite armor just fine, for some reason it is just this specific scenario.
[crash-2021-05-10_01.29.04-server.txt](https://github.com/MoriyaShiine/respawnable-pets/files/6450132/crash-2021-05-10_01.29.04-server.txt)
[crash-2021-05-10_01.41.32-server.txt](https://github.com/MoriyaShiine/respawnable-pets/files/6450133/crash-2021-05-10_01.41.32-server.txt)
Those are the two crash reports generated. My apologies if I've given a load of unnecessary information, I know absolutely nothing about coding and what info is necessary and I figured it would be better to give too much information than too little. I do have other mods installed. If it would be helpful I could also test with just one of the mods and see what happens. Lovely mod, by the way! Thank you

**Comment by MoriyaShiine** [comment]
Does this still happen in 1.17.1?
