### ISSUE TITLE
Requesting extra mod compatibility. 

### ISSUE THREAD

**Issue by githubbingitup** [MoriyaShiine/respawnable-pets#30]
Another way to make pets respawn.
Maybe right click or a chat command that applies to our active pets? Could be a config option.

This way we can use a mod that lets us avoid hitting our pets, but still have them respawn. (using a no friendly fire pet mod makes this one not usable)

Trying to use this on MC 1.16.5 with the mod Charm :)

**Comment by MoriyaShiine** [comment]
Charm has a config option for friendly fire, you can disable it for this mod to work
