### ISSUE TITLE
FoxEntity.tick lag?

### ISSUE THREAD

**Issue by VoidLock92** [MoriyaShiine/respawnable-pets#34]
For some reason when putting Respawnable Pets on my server during thunderstorms it causes FoxEntity.tick to lag the server. I used spark to track it down then removed the mod and the issue went away, I am not sure why this is caused by this mod but just wanted to report it :)

Here is a report from spark that I used to narrow this issue down.
https://spark.lucko.me/l37jAaWysO

If you need any more info please let me know!

Mod Version: respawnablepets-1.18-2.jar

**Comment by MoriyaShiine** [comment]
:what:

Are you absolutely certain this mod causes it? I don't see anything about it in the profile, and I only touch ticking briefly and it's very fast; due to it touching all entities, if it lags foxes then it should also lag all entities. I'm so confused lol

**Comment by VoidLock92** [comment]
Well I am only certain that when I take this mod out the issue that is shown in the profile from spark is corrected. It could be an interaction with another mod but I tried removing other mods one at a time first, with no solution. That is until I removed this mod. VERY strange indeed! Even stranger it was not even a fox causing the lag it was 2 dogs that I have tamed...

**Comment by MoriyaShiine** [comment]
This is all I do related to ticking, there's no way it would cause that much lag (it doesn't even run by default): https://github.com/MoriyaShiine/respawnable-pets/blob/2f50d8ed96bb33fe32fe2d589cce1f7106ab6bc4/src/main/java/moriyashiine/respawnablepets/mixin/LivingEntityMixin.java#L53

**Comment by VoidLock92** [comment]
Yeah, I am not sure to be honest. All I know is I tried removing several other mods I have that deal with pets such as Independent Pets first and the issue remained UNTIL I took out Respawnable Pets. 
![image](https://user-images.githubusercontent.com/21327041/151901425-a5faebd6-da18-4a35-a66d-434e6e8004cf.png)

[19:21:13] [main/INFO]: Loading 165 mods:
	- adorn 3.2.0+1.18.1
	- adventure-platform-fabric 5.0.0 via tabtps-fabric
	- adventurez 1.4.7
	- allstackable 1.5.2-1.18.1
	- appleskin 2.3.0+mc1.18.1
	- architectury 3.6.14
	- balm-fabric 2.4.0+0
	- basicshields 1.2.1-1.18.1
	- bclib 1.2.5
	- beautifiedchatserver-fabric 1.0
	- beenfo 1.18.1-fabric0.45.0-1.3.3
	- better_wandering_trader 1.8.0
	- betteranimalsplus 1.18.1-11.0.3
	- betterend 1.0.1
	- betternether 6.0.9
	- bewitchment 1.18-8
	- blue_endless_jankson 1.2.1 via jankson
	- bountiful 2.0.1
	- cardinal-components-base 4.0.1 via xp_storage
	- cardinal-components-entity 4.0.1 via xp_storage
	- cardinal-components-item 4.0.1 via xp_storage
	- carpet 1.4.57
	- cavetweaks 1.0
	- chunky 1.2.164
	- cloth-api 3.1.61
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.1.61 via cloth-api
	- cloth-common-events-v1 3.1.61 via cloth-api
	- cloth-config 6.1.48
	- cloth-config-lite 2.0.6 via omega-config-gui
	- cloth-datagen-api-v1 3.1.61 via cloth-api
	- cloth-utils-v1 3.1.61 via cloth-api
	- cloud 1.6.0 via tabtps-fabric
	- cloud_commandframework_cloud-brigadier_ 1.6.0 via cloud
	- cloud_commandframework_cloud-core_ 1.6.0 via cloud
	- cloud_commandframework_cloud-minecraft-extras 1.6.0 via tabtps-fabric
	- cloud_commandframework_cloud-services_ 1.6.0 via cloud
	- collective-fabric 3.14
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_typesafe_config 1.4.1 via tabtps-fabric
	- convenient-mobgriefing 2.0.2
	- crafttweaker 9.0.0+43
	- crowdin-translate 1.4+1.18 via beenfo
	- custom-fog 2.1.0
	- darkpaintings 9.0.2
	- dualwield 2.0.2
	- dynmap 3.3
	- fabric 0.46.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fabricshieldlib 1.4.5-1.18
	- fastbench 1.18.1-3
	- fastfurnace 1.18-4
	- fatxporbs 2.0.0
	- fiber 0.23.0-2 via collective-fabric
	- fixedanvilrepaircost-fabric 1.6
	- flan 1.18.1-1.6.9
	- flonters 1.3.0+1.18.1
	- friendsandfoes 1.2.2
	- geckolib3 3.0.32
	- graveyard 1.5
	- herdspanic 1.0.4
	- impaled 1.0.2
	- impersonate 2.4.0
	- indypets 0.8.1
	- ingredient-extension-api 2.0.1
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- kambrik 3.0.1-1.18
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- lithium 0.7.7
	- lovely_snails 1.0.3+1.18
	- luckperms 5.3.98
	- mavm 1.0.7a
	- minecraft 1.18.1
	- moreberries 1.4.5
	- morevillagers-fabric 3.1.1-SNAPSHOT
	- mythic-mounts 1.18-4.0
	- net_kyori_adventure-api 4.9.3 via adventure-platform-fabric
	- net_kyori_adventure-key 4.9.3 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.0.0 via adventure-platform-fabric
	- net_kyori_adventure-serializer-configurate4 4.9.3 via tabtps-fabric
	- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT via tabtps-fabric
	- net_kyori_adventure-text-minimessage 4.2.0-SNAPSHOT via tabtps-fabric
	- net_kyori_adventure-text-serializer-gson 4.9.3 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-legacy 4.9.3 via tabtps-fabric
	- net_kyori_adventure-text-serializer-plain 4.9.3 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- netherportalfix 9.0.0
	- omega-config 1.2.2-1.18.1 via friendsandfoes
	- omega-config-gui 1.2.1-1.18.1 via reroll
	- openloader 11.0.4
	- org_javassist_javassist 3.28.0-GA via crafttweaker
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_reflections_reflections 0.10.2 via crafttweaker
	- org_spongepowered_configurate-core 4.1.2 via tabtps-fabric
	- org_spongepowered_configurate-hocon 4.1.2 via tabtps-fabric
	- oro_config 2.1.0 via cavetweaks
	- patchouli 1.18.1-65-FABRIC
	- pehkui 3.1.0+1.14.4-1.18.1
	- phosphor 0.8.1
	- playerabilitylib 1.5.0
	- projectsavethepets 2.0.1+2021.eb4ca13d40
	- reach-entity-attributes 2.1.1 via bewitchment
	- reroll 1.4.0-1.18.1
	- seedfix 1.0.0 via terralith
	- serverstop 0.1.1
	- spark 1.7.2
	- step-height-entity-attribute 1.0.0 via bewitchment
	- strawdummy 1.6.0
	- tabtps-fabric 1.3.11
	- terraform-wood-api-v1 2.0.2 via bewitchment
	- terralith 2.0.12
	- trade 1.2.2
	- trinkets 3.1.0
	- villagers-follow-emeralds 1.2.0
	- wildworld 3.1.0+1.18
	- xp_storage 1.4.3+1.18
	- xp_storage_trinkets 0.1+1.18
	
I know I know... a lot of mods lol but still only reason I reported was it did not correct until I took out your mod is all. I very well could be an interaction, I am not pointing fingers by any means. I love your mods, just wanted to bring up the issue to see if there was some solution.

**Comment by MoriyaShiine** [comment]
Oh yeah don't worry about pointing fingers, if my mods cause problems then I'd like to know so I can fix them lol

I honestly have zero idea why this would happen. Maybe try binary searching (remove half of your mods at a time, but keeping respawnable pets) until it stops lagging? Of course, try with just respawnable pets first and see if that lags by itself, but if it doesn't then go the long way :p

**Comment by VoidLock92** [comment]
Hmm so I have done some more trouble shooting and the issue has cropped back up without your mod, so this can be closed. I am trying to narrow it down but it is strange as it is being hard to pin down and changing the way its acting. I am trying to do profiles to see a trace of the lag.

**Comment by MoriyaShiine** [comment]
I see, that's really weird. If you find what mod is causing it, get back to me and I might be able to see where it's happening and we can get a quick issue to the mod :)

**Comment by VoidLock92** [comment]
https://www.youtube.com/watch?v=ZEMj6_JBDSo
Thanks to the good people over at Fabric discord in the admin help section... there is a bug in MC that breaks AI pathfinding to blocks that are not rendered and causes cascading lag with some AI with the new AI system in thunder.
