### ISSUE TITLE
fabric server

### ISSUE THREAD

**Issue by ARESsamurai** [MoriyaShiine/respawnable-pets#35]
### Mod version

1.19.3

### A description of the issue

i am hosting a fabric server and i wanted to remove the mod but after I removed the .jar and the config file the server still 'deserialize" files from the mod and I can not find any other files left for the mod

**Comment by MoriyaShiine** [comment]
Those would be somewhere in the world folder, region files, or somewhere else (I don't know exactly where). They should only activate once per object that had data attached. Not really an issue with Respawnable Pets in particular, removing mods from existing worlds has never been supported for anything (mostly)

**Comment by ARESsamurai** [comment]
> Those would be somewhere in the world folder, region files, or somewhere else (I don't know exactly where). They should only activate once per object that had data attached. Not really an issue with Respawnable Pets in particular, removing mods from existing worlds has never been supported for anything (mostly)

ah thank you!
