### ISSUE TITLE
Pet duplication with Callable Horse and Iceandfire Dragons

### ISSUE THREAD

**Issue by rayhanhamada93** [MoriyaShiine/respawnable-pets#37]
### Mod version (NOT Minecraft version)

1.0.6.1

### A description of the issue

MC Version: 1.12.2
Mod Version: 1.0.6.1

Step to reproduce,

Callable horse:
1. Tame and make a horse respawnable on death.
2. Kill the horse.
3. Teleport your horse using callable horse keybind.
4. Sleep in your bed.
The callable horse mod will "spawn" a new horse, while respawnable pet respawns the previous horse, so there are 2 horses now.

Iceandfire dragons:
1. Tame a dragon and make them respawnable on death.
2. Put your dragon into a dragon horn (saving the dragon as an item form)
3. Sleep in your bed.
A dragon will "spawn" after you sleep, while the dragon in your dragon horn (as an item) still persist, which can be put out from the dragon horn, so there are 2 dragons now.

### Log or crash report

(none)

**Comment by MoriyaShiine** [comment]
1.12 has been unsupported for at least 5 years

**Comment by rayhanhamada93** [comment]
That's unfortunate, so there's no alternative way to fix it? Cuz I'd love to use this mod on rlcraft for respawnable dragon :c
