### ISSUE TITLE
Some incompatible modded mobs

### ISSUE THREAD

**Issue by inkdear** [MoriyaShiine/Respawnable-Pets#4]
From Ice and Fire:
- Amphithere - does not show message when right clicked at all, cannot be respawned
Other mobs work perfectly, including the dragons, which ordinarily drop corpses on death.

From Primitive Mobs:
- Baby creepers of all three varieties, which come from 'mystery eggs' (says 'mob does not belong to you')
- Tamed Chameleon (says 'mob does not belong to you')
Treasure Slime comes from the same mod and  works perfectly.

**Comment by MoriyaShiine** [comment]
There's nothing I can do about these. For the Primitive Mobs mobs, they don't have any form of owner tag, and I can't even see from the source if they're even tameable at all, it appears they aren't. For the Ice and Fire mobs, itemInteractionForEntity in Item only runs when processInteract in the entity returns false, so they're forcefully returning true for some reason. Ice and Fire should be easy to fix, just open an issue on their github and they'll know exactly what do to.

**Comment by MoriyaShiine** [comment]
It also appears that the Pixie does this too, be sure to mention that.

**Comment by inkdear** [comment]
Okay, will do!

**Comment by FamiliarGecko** [comment]
> There's nothing I can do about these. For the Primitive Mobs mobs, they don't have any form of owner tag, and I can't even see from the source if they're even tameable at all, it appears they aren't.

I checked the nbt of a Support Creeper that came from a mystery egg, and it seems that I found something. Not sure if this is what you were looking for? (underlined with red)
_(you can check their nbts with "/entitydata @e[type=primitivemobs:support_creeper,r=10] {}")_

![supportcreepertamed](https://user-images.githubusercontent.com/33727121/65921071-74e7b600-e3e1-11e9-9c3e-fbdd53c15392.png)
