### ISSUE TITLE
1.12.2 crash 

### ISSUE THREAD

**Issue by al-wei** [MoriyaShiine/respawnable-pets#40]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

respawnable-pets-1.0.6.1.jar

### A description of the issue

Inexplicable crash. I don't have any pets.

### Log or crash report

https://mclo.gs/ZJ7KLQr

**Comment by MoriyaShiine** [comment]
1.12.2 has been unsupported for over 4 years. Please verify that you are actually reading the check boxes you are marking.
