### ISSUE TITLE
pet cloning when far away from the real pet after sleeping

### ISSUE THREAD

**Issue by Biviho** [MoriyaShiine/respawnable-pets#5]
it appear that if you use the stone on a pet, set the pet to sit, than travel far away from the chunk, like 20 or more, and go to sleep, a new pet is generated

**Comment by MoriyaShiine** [comment]
What version is this on?

**Comment by Biviho** [comment]
on mc 1.12.2

**Comment by MoriyaShiine** [comment]
I meant the mod version

**Comment by Biviho** [comment]
oh, sorry, 1.0.5.1

**Comment by MoriyaShiine** [comment]
mc 1.12.2 is unsupported now, but maybe it's fixed on 1.14.4

**Comment by ridjack** [comment]
This issue is still present in 1.15.2.
